// Code generated by resetgen. DO NOT EDIT.

package structsflag

func (s *User) Reset() {
	s.ID = 0
	s.Name = ""
	s.Email = ""
}

func (s *Order) Reset() {
	s.ID = 0
	s.Total = 0.0
	s.Items = s.Items[:0]
}
