// Code generated by resetgen. DO NOT EDIT.

package basic

func (s *User) Reset() {
	s.ID = 0
	s.Name = "guest"
	s.Email = ""
	s.Tags = s.Tags[:0]
}

func (s *Config) Reset() {
	s.Debug = false
	s.Timeout = 30
	clear(s.Settings)
}
