// Code generated by resetgen. DO NOT EDIT.

package embedded

func (s *Metadata) Reset() {
	s.CreatedAt = 0
	s.UpdatedAt = 0
}

func (s *Entity) Reset() {
	s.Metadata.Reset()
	s.ID = ""
	s.Version = 1
}

func (s *Document) Reset() {
	if s.Metadata != nil {
		s.Metadata.Reset()
	}
	s.Title = ""
	s.Tags = s.Tags[:0]
}
