// Code generated by resetgen. DO NOT EDIT.

package directive

func (s *Request) Reset() {
	s.ID = ""
	s.Method = ""
	s.Path = ""
	clear(s.Headers)
	s.Body = s.Body[:0]
}

func (s *Response) Reset() {
	s.Status = 200
	s.Body = s.Body[:0]
	clear(s.Headers)
}

func (s *Config) Reset() {
	s.Host = ""
	s.Port = 8080
	s.Timeout = 0
}

func (s *User) Reset() {
	s.ID = 0
	s.Name = "unknown"
}
