// Code generated by resetgen. DO NOT EDIT.

package gogenerate

func (s *Request) Reset() {
	s.ID = ""
	s.Method = "GET"
	s.Path = ""
	clear(s.Headers)
	s.Body = s.Body[:0]
	clear(s.Query)
}

func (s *Response) Reset() {
	s.Status = 200
	clear(s.Headers)
	s.Body = s.Body[:0]
}
