package generator

import (
	"strconv"
	"strings"

	"github.com/flaticols/resetgen/internal/types"
)

// Generate produces Reset() methods for all structs in the file info.
func Generate(info *types.FileInfo) string {
	if len(info.Structs) == 0 {
		return ""
	}

	imports := collectImports(info.Structs)

	var b strings.Builder
	b.Grow(1024)

	b.WriteString("// Code generated by resetgen. DO NOT EDIT.\n\n")
	b.WriteString("package ")
	b.WriteString(info.PkgName)
	b.WriteString("\n")

	if len(imports) > 0 {
		b.WriteString("\nimport (\n")
		for _, imp := range imports {
			b.WriteString("\t\"")
			b.WriteString(imp)
			b.WriteString("\"\n")
		}
		b.WriteString(")\n")
	}
	b.WriteString("\n")

	for i, s := range info.Structs {
		if i > 0 {
			b.WriteString("\n")
		}
		generateReset(&b, &s)
	}

	return b.String()
}

// GenerateStruct produces a Reset() method for a single struct.
func GenerateStruct(s *types.StructInfo) string {
	var b strings.Builder
	b.Grow(512)
	generateReset(&b, s)
	return b.String()
}

func collectImports(structs []types.StructInfo) []string {
	pkgSet := make(map[string]bool)

	for _, s := range structs {
		for _, f := range s.Fields {
			if f.Action == types.ActionIgnore {
				continue
			}
			if pkg := extractPackage(f.TypeStr); pkg != "" {
				pkgSet[pkg] = true
			}
		}
	}

	var imports []string
	for pkg := range pkgSet {
		imports = append(imports, pkg)
	}
	return imports
}

func extractPackage(typeStr string) string {
	t := strings.TrimPrefix(typeStr, "*")
	idx := strings.Index(t, ".")
	if idx <= 0 {
		return ""
	}

	pkg := t[:idx]
	switch pkg {
	case "time":
		return "time"
	case "netip":
		return "net/netip"
	case "context":
		return "context"
	case "io":
		return "io"
	case "os":
		return "os"
	case "sync":
		return "sync"
	case "atomic":
		return "sync/atomic"
	case "json":
		return "encoding/json"
	case "xml":
		return "encoding/xml"
	case "http":
		return "net/http"
	case "url":
		return "net/url"
	case "sql":
		return "database/sql"
	case "regexp":
		return "regexp"
	case "bytes":
		return "bytes"
	case "strings":
		return "strings"
	case "math":
		return "math"
	case "rand":
		return "math/rand"
	case "big":
		return "math/big"
	default:
		return pkg
	}
}

func generateReset(b *strings.Builder, s *types.StructInfo) {
	b.WriteString("func (s *")
	b.WriteString(s.Name)
	b.WriteString(") Reset() {\n")

	for _, f := range s.Fields {
		if f.Action == types.ActionIgnore {
			continue
		}
		generateFieldReset(b, &f)
	}

	b.WriteString("}\n")
}

func generateFieldReset(b *strings.Builder, f *types.FieldInfo) {
	b.WriteString("\t")
	accessor := "s." + f.Name

	switch f.Action {
	case types.ActionDefault:
		generateDefaultReset(b, f, accessor)
	case types.ActionZero:
		generateZeroReset(b, f, accessor)
	}
}

func generateDefaultReset(b *strings.Builder, f *types.FieldInfo, accessor string) {
	switch f.Kind {
	case types.KindSlice, types.KindMap:
		generateZeroReset(b, f, accessor)
	case types.KindPointer:
		b.WriteString("if ")
		b.WriteString(accessor)
		b.WriteString(" != nil {\n")
		b.WriteString("\t\t*")
		b.WriteString(accessor)
		b.WriteString(" = ")
		b.WriteString(formatDefault(f))
		b.WriteString("\n\t}\n")
	case types.KindStruct:
		if f.IsEmbedded {
			b.WriteString(accessor)
			b.WriteString(".Reset()\n")
		} else {
			b.WriteString(accessor)
			b.WriteString(" = ")
			b.WriteString(formatDefault(f))
			b.WriteString("\n")
		}
	default:
		b.WriteString(accessor)
		b.WriteString(" = ")
		b.WriteString(formatDefault(f))
		b.WriteString("\n")
	}
}

func generateZeroReset(b *strings.Builder, f *types.FieldInfo, accessor string) {
	if f.IsEmbedded {
		if isExternalType(f.TypeStr) {
			b.WriteString(accessor)
			b.WriteString(" = ")
			b.WriteString(zeroValue(f.TypeStr))
			b.WriteString("\n")
			return
		}
		switch f.Kind {
		case types.KindPointer:
			b.WriteString("if ")
			b.WriteString(accessor)
			b.WriteString(" != nil {\n")
			b.WriteString("\t\t")
			b.WriteString(accessor)
			b.WriteString(".Reset()\n")
			b.WriteString("\t}\n")
		default:
			b.WriteString(accessor)
			b.WriteString(".Reset()\n")
		}
		return
	}

	switch f.Kind {
	case types.KindSlice:
		b.WriteString(accessor)
		b.WriteString(" = ")
		b.WriteString(accessor)
		b.WriteString("[:0]\n")
	case types.KindMap:
		b.WriteString("clear(")
		b.WriteString(accessor)
		b.WriteString(")\n")
	case types.KindPointer:
		b.WriteString(accessor)
		b.WriteString(" = nil\n")
	case types.KindStruct:
		if isExternalType(f.TypeStr) {
			b.WriteString(accessor)
			b.WriteString(" = ")
			b.WriteString(f.TypeStr)
			b.WriteString("{}\n")
		} else {
			b.WriteString(accessor)
			b.WriteString(".Reset()\n")
		}
	case types.KindArray:
		b.WriteString(accessor)
		b.WriteString(" = ")
		b.WriteString(f.TypeStr)
		b.WriteString("{}\n")
	case types.KindChan, types.KindInterface:
		b.WriteString(accessor)
		b.WriteString(" = nil\n")
	default:
		if isLocalStructType(f.TypeStr) {
			b.WriteString(accessor)
			b.WriteString(".Reset()\n")
		} else {
			b.WriteString(accessor)
			b.WriteString(" = ")
			b.WriteString(zeroValue(f.TypeStr))
			b.WriteString("\n")
		}
	}
}

func isExternalType(typeStr string) bool {
	t := strings.TrimPrefix(typeStr, "*")
	return strings.Contains(t, ".")
}

func isLocalStructType(typeStr string) bool {
	if strings.HasPrefix(typeStr, "*") ||
		strings.HasPrefix(typeStr, "[]") ||
		strings.HasPrefix(typeStr, "map[") ||
		strings.HasPrefix(typeStr, "chan") ||
		strings.HasPrefix(typeStr, "func") {
		return false
	}
	if strings.Contains(typeStr, ".") {
		return false
	}
	switch typeStr {
	case "string", "bool", "error",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune",
		"float32", "float64",
		"complex64", "complex128",
		"interface{}", "any":
		return false
	}
	return len(typeStr) > 0 && typeStr[0] >= 'A' && typeStr[0] <= 'Z'
}

func formatDefault(f *types.FieldInfo) string {
	switch f.TypeStr {
	case "string":
		return strconv.Quote(f.Default)
	case "bool":
		if f.Default == "true" || f.Default == "1" {
			return "true"
		}
		return "false"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return f.Default
	default:
		return f.Default
	}
}

func zeroValue(typeStr string) string {
	switch typeStr {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return "0"
	case "error":
		return "nil"
	default:
		if strings.HasPrefix(typeStr, "*") ||
			strings.HasPrefix(typeStr, "[]") ||
			strings.HasPrefix(typeStr, "map[") ||
			strings.HasPrefix(typeStr, "chan") ||
			strings.HasPrefix(typeStr, "func") ||
			typeStr == "interface{}" || typeStr == "any" {
			return "nil"
		}
		return typeStr + "{}"
	}
}
