// Code generated by resetgen. DO NOT EDIT.

package selective

func (s *PooledRequest) Reset() {
	s.ID = ""
	s.Method = "GET"
	s.Path = ""
	clear(s.Headers)
	s.Body = s.Body[:0]
}

func (s *PooledResponse) Reset() {
	s.Status = 200
	s.Body = s.Body[:0]
}

func (s *MixedStruct) Reset() {
	s.RequestID = ""
	s.Buffer = s.Buffer[:0]
	s.Counter = 0
}
