// Code generated by resetgen. DO NOT EDIT.

package complex

import (
	"net/netip"
	"time"
)

func (s *Metadata) Reset() {
	s.ID = 0
	s.CreatedAt = time.Time{}
	s.UpdatedAt = time.Time{}
	s.Version = 1
}

func (s *Address) Reset() {
	s.Street = ""
	s.City = ""
	s.State = ""
	s.PostalCode = ""
	s.Country = "US"
}

func (s *Contact) Reset() {
	s.Email = ""
	s.Phone = ""
	s.PhoneAlt = nil
	s.Preferences = s.Preferences[:0]
}

func (s *Credentials) Reset() {
	s.PasswordHash = s.PasswordHash[:0]
	s.Salt = s.Salt[:0]
	s.TokenHash = nil
	clear(s.Sessions)
	clear(s.Permissions)
}

func (s *Profile) Reset() {
	s.DisplayName = "Anonymous"
	s.AvatarURL = ""
	s.Bio = ""
	s.Location = nil
	clear(s.Social)
	s.Tags = s.Tags[:0]
	s.Verified = false
}

func (s *Subscription) Reset() {
	s.PlanID = "free"
	s.StartedAt = time.Time{}
	s.ExpiresAt = nil
	s.AutoRenew = true
	s.PaymentInfo = nil
}

func (s *UsageStats) Reset() {
	s.RequestCount = 0
	s.BytesIn = 0
	s.BytesOut = 0
	s.ErrorCount = 0
	s.LastActivityAt = 0
	s.Endpoints = s.Endpoints[:0]
	clear(s.StatusCodes)
}

func (s *RateLimit) Reset() {
	s.Limit = 100
	s.Remaining = 100
	s.ResetAt = 0
	s.Tokens = s.Tokens[:0]
}

func (s *User) Reset() {
	s.Metadata.Reset()
	s.Username = ""
	s.Email = ""
	s.DisplayName = "Guest"
	s.Locale = "en-US"
	s.Timezone = "UTC"
	s.Active = false
	s.Verified = false
	s.Suspended = false
	s.DeletedAt = nil
	s.Profile = nil
	s.Contact = nil
	s.Address.Reset()
	s.Credentials.Reset()
	s.Subscription.Reset()
	s.Subscriptions = s.Subscriptions[:0]
	s.Usage.Reset()
	s.RateLimit.Reset()
	s.Roles = s.Roles[:0]
	s.Permissions = s.Permissions[:0]
	s.Groups = s.Groups[:0]
	s.Followers = s.Followers[:0]
	s.Following = s.Following[:0]
	s.BlockedUsers = s.BlockedUsers[:0]
	clear(s.Settings)
	clear(s.Preferences)
	clear(s.FeatureFlags)
	clear(s.CustomFields)
	s.Addresses = s.Addresses[:0]
	s.PaymentMethods = s.PaymentMethods[:0]
}

func (s *HTTPRequest) Reset() {
	s.ID = ""
	s.TraceID = ""
	s.SpanID = ""
	s.ParentID = ""
	s.Method = "GET"
	s.Path = ""
	s.RawQuery = ""
	s.Proto = "HTTP/1.1"
	s.Host = ""
	s.RemoteAddr = ""
	s.HeaderKeys = s.HeaderKeys[:0]
	s.HeaderValues = s.HeaderValues[:0]
	s.QueryKeys = s.QueryKeys[:0]
	s.QueryValues = s.QueryValues[:0]
	s.Body = s.Body[:0]
	s.ContentType = ""
	s.ContentLen = 0
	clear(s.FormData)
	clear(s.Cookies)
	s.AuthType = ""
	s.AuthToken = ""
	s.UserID = nil
	s.SessionID = nil
	s.ContextKeys = s.ContextKeys[:0]
	s.ContextValues = s.ContextValues[:0]
	s.StartTime = 0
	s.ParseTime = 0
	s.AuthTime = 0
	s.StatusCode = 200
	s.BytesWritten = 0
	s.Errors = s.Errors[:0]
	s.Warnings = s.Warnings[:0]
}

func (s *HTTPResponse) Reset() {
	s.StatusCode = 200
	s.StatusText = "OK"
	s.HeaderKeys = s.HeaderKeys[:0]
	s.HeaderValues = s.HeaderValues[:0]
	s.Body = s.Body[:0]
	s.BodyLen = 0
	s.Compressed = false
	s.CompressType = ""
	s.Chunked = false
	s.Chunks = s.Chunks[:0]
	s.SetCookies = s.SetCookies[:0]
	s.CacheControl = ""
	s.ETag = ""
	s.LastModified = 0
	s.StartTime = 0
	s.FirstByte = 0
	s.EndTime = 0
}

func (s *DatabaseQuery) Reset() {
	s.SQL = ""
	s.Args = s.Args[:0]
	s.ArgTypes = s.ArgTypes[:0]
	s.StmtName = ""
	s.StmtCached = false
	s.TxID = nil
	s.TxIsolation = ""
	s.Columns = s.Columns[:0]
	s.ColumnTypes = s.ColumnTypes[:0]
	s.Rows = s.Rows[:0]
	s.RowsAffected = 0
	s.LastInsertID = 0
	s.Offset = 0
	s.Limit = 100
	s.TotalCount = 0
	s.PrepareTime = 0
	s.ExecuteTime = 0
	s.FetchTime = 0
	s.Error = nil
	s.Warnings = s.Warnings[:0]
	s.ExplainPlan = ""
	s.SlowQuery = false
}

func (s *CacheEntry) Reset() {
	s.Key = ""
	s.Value = s.Value[:0]
	s.ValueType = ""
	s.ExpiresAt = 0
	s.CreatedAt = 0
	s.AccessedAt = 0
	s.AccessCount = 0
	s.Tags = s.Tags[:0]
	s.Dependencies = s.Dependencies[:0]
	clear(s.Metadata)
	s.Compressed = false
	s.OriginalSize = 0
	s.Version = 0
	s.ETag = ""
	s.NoExpire = false
	s.NoEvict = false
	s.Dirty = false
}

func (s *LogEntry) Reset() {
	s.Timestamp = 0
	s.Level = "INFO"
	s.Message = ""
	s.Logger = ""
	s.TraceID = ""
	s.SpanID = ""
	s.RequestID = ""
	s.UserID = ""
	s.SessionID = ""
	s.File = ""
	s.Line = 0
	s.Function = ""
	s.Package = ""
	s.Error = nil
	s.ErrorType = ""
	s.StackTrace = ""
	clear(s.Fields)
	s.Tags = s.Tags[:0]
	s.Method = ""
	s.Path = ""
	s.StatusCode = 0
	s.Duration = 0
	s.Query = ""
	s.QueryTime = 0
	s.RowCount = 0
	s.Sampled = false
	s.SampleRate = 1.0
}

func (s *NetworkConnection) Reset() {
	s.ID = ""
	s.Protocol = "tcp"
	s.LocalAddr = netip.Addr{}
	s.LocalPort = 0
	s.RemoteAddr = netip.Addr{}
	s.RemotePort = 0
	s.State = ""
	s.Connected = false
	s.Encrypted = false
	s.Compressed = false
	s.TLSVersion = ""
	s.CipherSuite = ""
	s.ServerName = ""
	s.Certificates = s.Certificates[:0]
	s.ReadBuffer = s.ReadBuffer[:0]
	s.WriteBuffer = s.WriteBuffer[:0]
	s.BytesRead = 0
	s.BytesWritten = 0
	s.PacketsIn = 0
	s.PacketsOut = 0
	s.ConnectedAt = 0
	s.LastReadAt = 0
	s.LastWriteAt = 0
	s.ReadErrors = 0
	s.WriteErrors = 0
	s.LastError = nil
	s.Tags = s.Tags[:0]
	clear(s.Metadata)
}

func (s *WorkerTask) Reset() {
	s.ID = ""
	s.Type = ""
	s.Queue = "default"
	s.Priority = 0
	s.Payload = s.Payload[:0]
	s.PayloadType = ""
	clear(s.Args)
	s.ScheduledAt = 0
	s.StartedAt = 0
	s.CompletedAt = 0
	s.Deadline = 0
	s.Attempts = 0
	s.MaxAttempts = 3
	s.RetryDelay = 0
	s.RetryErrors = s.RetryErrors[:0]
	s.Progress = 0
	s.ProgressMsg = ""
	s.Checkpoints = s.Checkpoints[:0]
	s.Result = s.Result[:0]
	s.ResultType = ""
	s.Error = nil
	s.DependsOn = s.DependsOn[:0]
	s.Blocks = s.Blocks[:0]
	s.Tags = s.Tags[:0]
	clear(s.Labels)
	s.TraceID = ""
	s.SpanID = ""
	s.ParentID = ""
}

func (s *EventMessage) Reset() {
	s.ID = ""
	s.Type = ""
	s.Source = ""
	s.Subject = ""
	s.ContentType = "application/json"
	s.Data = s.Data[:0]
	s.DataSchema = ""
	s.Topic = ""
	s.Partition = 0
	s.Key = s.Key[:0]
	clear(s.Headers)
	s.Timestamp = 0
	s.PublishedAt = 0
	s.ReceivedAt = 0
	s.ProcessedAt = 0
	s.DeliveryMode = 0
	s.Redelivered = false
	s.ReplyTo = ""
	s.CorrelationID = ""
	s.Acknowledged = false
	s.AckTime = 0
	s.NackReason = ""
	s.TraceID = ""
	s.SpanID = ""
	clear(s.TraceContext)
	s.Error = nil
	s.RetryCount = 0
	s.DeadLettered = false
}
